message = "enter some value"
days = 20
price = 9.99
valid_number = True
exit_input = False
list_of_days = [20, 40, 50]
list_of_month = ["January", "February", "March"]
set_of_days = {20, 45, 100}
days_and_unit = {"days": "10", "unit": "minutes"}